import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

export async function seedPartners(prisma: PrismaClient) {
  const password = await bcrypt.hash('dogao@2026', 10);

  const partners = [
    {
      id: 'mly7z2p8x99110d3v4a5l6k7j',
      name: 'Parceiro temporário 1',
      cnpj: '00000000000001',
      phone: '51000000001',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'nmz8a3q9y00221e4w5b6m7l8k',
      name: 'Parceiro temporário 2',
      cnpj: '00000000000002',
      phone: '51000000002',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'on29b4r0z11332f5x6c7n8m9l',
      name: 'Parceiro temporário 3',
      cnpj: '00000000000003',
      phone: '51000000003',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'po30c5s1a22443g6y7d8o9n0m',
      name: 'Parceiro temporário 4',
      cnpj: '00000000000004',
      phone: '51000000004',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'qp41d6t2b33554h7z8e9p0o1n',
      name: 'Parceiro temporário 5',
      cnpj: '00000000000005',
      phone: '51000000005',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'rq52e7u3c44665i8a9f0q1p2o',
      name: 'Parceiro temporário 6',
      cnpj: '00000000000006',
      phone: '51000000006',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'sr63f8v4d55776j9b0g1r2q3p',
      name: 'Parceiro temporário 7',
      cnpj: '00000000000007',
      phone: '51000000007',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'ts74g9w5e66887k0c1h2s3r4q',
      name: 'Parceiro temporário 8',
      cnpj: '00000000000008',
      phone: '51000000008',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'ut85h0x6f77998l1d2i3t4s5r',
      name: 'Parceiro temporário 9',
      cnpj: '00000000000009',
      phone: '51000000009',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'vu96i1y7g88009m2e3j4u5t6s',
      name: 'Parceiro temporário 10',
      cnpj: '00000000000010',
      phone: '51000000010',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'wv07j2z8h99110n3f4k5v6u7t',
      name: 'Parceiro temporário 11',
      cnpj: '00000000000011',
      phone: '51000000011',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'xw18k3a9i00221o4g5l6w7v8u',
      name: 'Parceiro temporário 12',
      cnpj: '00000000000012',
      phone: '51000000012',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'yx29l4b0j11332p5h6m7x8w9v',
      name: 'Parceiro temporário 13',
      cnpj: '00000000000013',
      phone: '51000000013',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'zy30m5c1k22443q6i7n8y9x0w',
      name: 'Parceiro temporário 14',
      cnpj: '00000000000014',
      phone: '51000000014',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'az41n6d2l33554r7j8o9z0y1x',
      name: 'Parceiro temporário 15',
      cnpj: '00000000000015',
      phone: '51000000015',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'ba52o7e3m44665s8k9p0a1z2y',
      name: 'Parceiro temporário 16',
      cnpj: '00000000000016',
      phone: '51000000016',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'cb63p8f4n55776t9l0q1b2a3z',
      name: 'Parceiro temporário 17',
      cnpj: '00000000000017',
      phone: '51000000017',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'dc74q9g5o66887u0m1r2c3b4a',
      name: 'Parceiro temporário 18',
      cnpj: '00000000000018',
      phone: '51000000018',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'ed85r0h6p77998v1n2s3d4c5b',
      name: 'Parceiro temporário 19',
      cnpj: '00000000000019',
      phone: '51000000019',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
    {
      id: 'fe96s1i7q88009w2o3t4e5d6c',
      name: 'Parceiro temporário 20',
      cnpj: '00000000000020',
      phone: '51000000020',
      description: 'Descricao da entidade parceira',
      website: '',
      facebook: '',
      instagram: '',
      addressInLine: '',
      street: '',
      number: '',
      neighborhood: '',
      city: '',
      state: '',
      zipCode: '',
      complement: '',
      responsibleName: '',
      responsiblePhone: '',
      approved: false,
      password,
      active: false,
    },
  ];

  for (const partner of partners) {
    const exists = await prisma.partner.findFirst({
      where: { id: partner.id },
    });

    if (exists) continue;

    await prisma.partner.create({
      data: partner,
    });
  }
}
