export enum OrderStatsEnum {
  DIGITATION = 'DIGITATION',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT = 'PAYMENT',
  NEW = 'NEW',
  QUEUE = 'QUEUE',
  PRODUCTION = 'PRODUCTION',
  EXPEDITION = 'EXPEDITION',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
